/**
 * compat — M2 移动端组件覆盖（composer/header 键盘专项）。
 * 规则全部落在 @media (max-width: 1023px) 与 (pointer: coarse) 内；桌面零影响。
 * 所有哈希类已在 selector-map.ts 登记（dshVersion 0.1.1-rc.2）。
 * 玻璃拟态：background 双声明 = 纯色 fallback + color-mix（旧引擎自动回退）。
 * 高度动画：CSS 只过渡 max-width；height 由 JS FLIP 仅在 focus/blur 状态切换时动画
 * （打字增长即时，避免逐键动画）。
 */

const LINES = [
  '@media (max-width: 1023px) {',
  '  /* ---- 键盘：dvh 双声明（100% 兜底 + 100dvh 跟随浏览器可视高度）---- */',
  '  html, body, #root {',
  '    height: 100%;',
  '    height: 100dvh;',
  '  }',
  '',
  '  /* ---- iOS Safari 输入聚焦防自动放大：聚焦字号 <16px 的输入/编辑区会整页放大 ---- */',
  '  /* 16px 是硬阈值（>=16px 不再放大）；只加在移动断点内（桌面零影响），不碰双指捏合缩放 */',
  '  input, textarea, select, [contenteditable="true"] {',
  '    font-size: 16px !important;',
  '  }',
  '  /* composer 输入区与占位提示同升 16px，避免输入文字与 placeholder 大小不一致 */',
  '  [data-mobile-nav="frame"] [data-composer-input],',
  '  [data-mobile-nav="frame"] [data-composer-placeholder] {',
  '    font-size: 16px !important;',
  '  }',
  '',
  '  /* ---- 悬浮玻璃卡片（glass 视觉资产迁移）---- */',
  '  [data-mobile-nav="frame"] .uV2eYG_card {',
  '    border-radius: 20px !important;',
  '    background: var(--dsw-alias-bg-layer-1) !important;',
  '    background: color-mix(in srgb, var(--dsw-alias-bg-layer-1) 72%, transparent) !important;',
  '    backdrop-filter: blur(22px) saturate(180%);',
  '    -webkit-backdrop-filter: blur(22px) saturate(180%);',
  '    box-shadow: 0 14px 40px rgba(0, 0, 0, 0.14), inset 0 1px 0 rgba(255, 255, 255, 0.5);',
  '    max-width: min(86%, 460px) !important;',
  '    /* 只过渡 max-width；height 由 JS FLIP 在 focus/blur 时接管 */',
  '    transition: max-width .32s cubic-bezier(.32, .72, .24, 1);',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_card:focus-within {',
  '    max-width: 100% !important;',
  '  }',
  '  /* 输入区：未聚焦紧凑一行（mirror 24px），聚焦展开约 2.5 行 */',
  '  [data-mobile-nav="frame"] .uV2eYG_mirror {',
  '    min-height: 24px !important;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_card:focus-within .uV2eYG_mirror {',
  '    min-height: 60px !important;',
  '  }',
  '',
  '  /* ---- 一行契约：add/modes/model/send 同一行不换行；固定控件豁免收缩 ---- */',
  '  [data-mobile-nav="frame"] .uV2eYG_row {',
  '    flex-wrap: nowrap !important;',
  '    gap: 6px;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_tools,',
  '  [data-mobile-nav="frame"] .uV2eYG_modes {',
  '    gap: 6px;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_trailing {',
  '    flex: 1 1 auto !important;',
  '    justify-content: flex-end;',
  '    gap: 6px;',
  '  }',
  '  /* 固定控件钉死：add 28 / primary 34（mex 实测被压扁的瓶颈）*/',
  '  [data-mobile-nav="frame"] .uV2eYG_add,',
  '  [data-mobile-nav="frame"] .uV2eYG_primary {',
  '    flex: none !important;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_primary {',
  '    width: 34px !important;',
  '    height: 34px !important;',
  '  }',
  '  /* 模型选择器：可收缩 + ellipsis；effort 芯片不收缩 */',
  '  [data-mobile-nav="frame"] ._7KE1Ra_trigger {',
  '    max-width: min(100%, 180px) !important;',
  '    min-width: 0;',
  '  }',
  '  [data-mobile-nav="frame"] ._7KE1Ra_triggerLabel {',
  '    overflow: hidden;',
  '    text-overflow: ellipsis;',
  '    white-space: nowrap;',
  '    min-width: 0;',
  '  }',
  '',
  '  /* ---- 底部安全区（home indicator）---- */',
  '  [data-mobile-nav="frame"] .uV2eYG_root {',
  '    padding-bottom: calc(8px + env(safe-area-inset-bottom, 0px)) !important;',
  '  }',
  '',
  '  /* ---- 汉堡避让：聊天头标题左移，避免被 44px 汉堡盖住 ---- */',
  '  [data-mobile-nav="frame"] .wSkVaW_titleRow {',
  '    padding-left: 52px;',
  '  }',
  '  /* 汉堡避让：标签行（对话/轨迹等）同样让出左缘 */',
  '  [data-mobile-nav="frame"] .wSkVaW_tabs {',
  '    margin-left: 52px;',
  '  }',
  '',
  '  /* ---- M6 页头标题簇横向可滑：单行不换行，溢出靠滑 ---- */',
  '  /* 两级属性分工（勿混）：html[data-xc-hscroll] = 功能开关总闸（header-scroll 任务按',
  '     config.headerScroll 打/摘）→ 驱动 overflow 等布局改动，开启时常驻；',
  '     [data-xc-hscroll-more] = 元素级溢出态 → 只驱动 mask。JS 永不改 overflow，',
  '     所以溢出态翻转不会引起布局跳动。 */',
  '  html[data-xc-hscroll] [data-mobile-nav="frame"] .wSkVaW_titleRow .wSkVaW_titleCluster {',
  '    overflow-x: auto;',
  '    overflow-y: hidden;',
  '    flex-wrap: nowrap;',
  '    scrollbar-width: none;',
  '    overscroll-behavior-x: contain;',
  '    padding-block: 2px;',
  '    margin-block: -2px;',
  '    -webkit-tap-highlight-color: transparent;',
  '  }',
  '  /* 禁则：本容器不得加 transform / filter / backdrop-filter / will-change / -webkit-overflow-scrolling ——',
  '     那会成为 fixed 后代的包含块，把 misc.css 的页头居中菜单拽坏。 */',
  '  html[data-xc-hscroll] [data-mobile-nav="frame"] .wSkVaW_titleRow .wSkVaW_titleCluster::-webkit-scrollbar {',
  '    display: none;',
  '  }',
  '  /* 徽标不压扁 + 反制 dsh-token-usage-xc 的 ≤380px 换行（页头不长高）：',
  '     对方规则非 important、specificity 仅 (0,1,0)，本链四级 class/attr + important 稳赢。',
  '     徽标 flex 基准的事实依据：徽标根是槽锚 div[data-slot]（display:contents）的子女，',
  '     不生成盒子的锚拿不到 flex，故两臂并列（第一臂保留以兼容 vendor 日后不再',
  '     display:contents）；第二臂具体度 (0,5,1) > token-usage-xc 的',
  '     [data-slot=...]>[class*="_root"] (0,2,0)，无需 important。 */',
  '  html[data-xc-hscroll] [data-mobile-nav="frame"] .wSkVaW_titleRow .wSkVaW_headerActions {',
  '    flex: 0 0 auto !important;',
  '    flex-wrap: nowrap !important;',
  '  }',
  '  html[data-xc-hscroll] [data-mobile-nav="frame"] .wSkVaW_titleRow .wSkVaW_headerActions > *:',
  '  html[data-xc-hscroll] [data-mobile-nav="frame"] .wSkVaW_titleRow .wSkVaW_headerActions [data-slot] > * {',
  '    flex: 0 0 auto;',
  '  }',
  '  /* 标题地板（实测必需，非润色）：vendor 给 crumbs 设了 flex-shrink:1 + min-width:0，',
  '     而徽标组 flex:none 不可收缩 → 挤压全部落在标题上，徽标一多会话名就被压成 0 宽。',
  '     96px ≈ 6 个 14px 汉字，标题保持可辨识，超出部分改由"溢出 + 滑动"承担。 */',
  '  html[data-xc-hscroll] [data-mobile-nav="frame"] .wSkVaW_titleRow .wSkVaW_crumbs {',
  '    min-width: 96px;',
  '  }',
  '  /* 右缘渐隐（溢出提示）：mask 定位区是元素 border box、不随内容滚动 →',
  '     渐变天然钉在可见右缘，无需 JS 量坐标。 */',
  '  html[data-xc-hscroll] [data-mobile-nav="frame"] .wSkVaW_titleRow .wSkVaW_titleCluster[data-xc-hscroll-more] {',
  '    -webkit-mask-image: linear-gradient(to right, #000 calc(100% - 28px), transparent);',
  '    mask-image: linear-gradient(to right, #000 calc(100% - 28px), transparent);',
  '  }',
  '  /* mask 会连坐裁掉后代：jobs 下拉 ul[aria-label] 是 actions 槽内联节点（misc.css 强制',
  '     其 fixed 居中），弹层在场时撤 mask。dshu-pop / schedule 菜单实测走 body portal，',
  '     本就裁不到，列入 :has 属无害冗余。 */',
  '  html[data-xc-hscroll] [data-mobile-nav="frame"] .wSkVaW_titleRow .wSkVaW_titleCluster[data-xc-hscroll-more]:has([role="menu"], [role="dialog"], ul[aria-label]) {',
  '    -webkit-mask-image: none;',
  '    mask-image: none;',
  '  }',
  '  /* 移动端只隐藏官方 Session log 下载（dsh-session-log-export 的 more 按钮）。',
  '     旧实现整槽 display:none 会连坐 utilities 槽里的第三方入口——实测误伤',
  '     dsh-better-sidebar 底部面板切换钮（图标 0x0 不可点，移动端插件全废）。',
  '     哈希漂移兜底：按钮在移动端恢复可见，无功能损害（nL4_yW 已登记 canary）。 */',
  '  [data-mobile-nav="frame"] [data-slot="conversation.session.header.utilities"] .nL4_yW_moreButton {',
  '    display: none !important;',
  '  }',
  '  /* 移动端隐藏官方 open-in-app「在资源管理器/应用中打开」split 按钮：',
  '     唤起的是 host 侧桌面应用，手机浏览器点了无任何可达效果。哈希类无',
  '     data-* 锚，已登记 canary；漂移兜底：按钮恢复可见（无害）。 */',
  '  [data-mobile-nav="frame"] [data-slot="conversation.session.header.utilities"] .CAgGvG_split {',
  '    display: none !important;',
  '  }',
  '}',
  '',
  '@media (max-width: 1023px) and (pointer: coarse) {',
  '  /* 44px 触控热区：::after 扩展命中区，不动视觉布局（TecFancy D6 手法）*/',
  '  [data-mobile-nav="frame"] .uV2eYG_add,',
  '  [data-mobile-nav="frame"] .uV2eYG_primary {',
  '    position: relative;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_add::after,',
  '  [data-mobile-nav="frame"] .uV2eYG_primary::after {',
  "    content: '';",
  '    position: absolute;',
  '    inset: -8px;',
  '  }',
  '}',
]

export const COMPAT_CSS = LINES.join('\n')
