/**
 * compat — M2 移动端组件覆盖（composer/header 键盘专项）。
 * 规则全部落在 @media (max-width: 1023px) 与 (pointer: coarse) 内；桌面零影响。
 * 所有哈希类已在 selector-map.ts 登记（dshVersion 0.1.1-rc.2）。
 * 玻璃拟态：background 双声明 = 纯色 fallback + color-mix（旧引擎自动回退）。
 * 高度动画：CSS 只过渡 max-width；height 由 JS FLIP 仅在 focus/blur 状态切换时动画
 * （打字增长即时，避免逐键动画）。
 */

const LINES = [
  '@media (max-width: 1023px) {',
  '  /* ---- 键盘：dvh 双声明（100% 兜底 + 100dvh 跟随浏览器可视高度）---- */',
  '  html, body, #root {',
  '    height: 100%;',
  '    height: 100dvh;',
  '  }',
  '',
  '  /* ---- 悬浮玻璃卡片（glass 视觉资产迁移）---- */',
  '  [data-mobile-nav="frame"] .uV2eYG_card {',
  '    border-radius: 20px !important;',
  '    background: var(--dsw-alias-bg-layer-1) !important;',
  '    background: color-mix(in srgb, var(--dsw-alias-bg-layer-1) 72%, transparent) !important;',
  '    backdrop-filter: blur(22px) saturate(180%);',
  '    -webkit-backdrop-filter: blur(22px) saturate(180%);',
  '    box-shadow: 0 14px 40px rgba(0, 0, 0, 0.14), inset 0 1px 0 rgba(255, 255, 255, 0.5);',
  '    max-width: min(86%, 460px) !important;',
  '    /* 只过渡 max-width；height 由 JS FLIP 在 focus/blur 时接管 */',
  '    transition: max-width .32s cubic-bezier(.32, .72, .24, 1);',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_card:focus-within {',
  '    max-width: 100% !important;',
  '  }',
  '  /* 输入区：未聚焦紧凑一行（mirror 24px），聚焦展开约 2.5 行 */',
  '  [data-mobile-nav="frame"] .uV2eYG_mirror {',
  '    min-height: 24px !important;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_card:focus-within .uV2eYG_mirror {',
  '    min-height: 60px !important;',
  '  }',
  '',
  '  /* ---- 一行契约：add/modes/model/send 同一行不换行；固定控件豁免收缩 ---- */',
  '  [data-mobile-nav="frame"] .uV2eYG_row {',
  '    flex-wrap: nowrap !important;',
  '    gap: 6px;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_tools,',
  '  [data-mobile-nav="frame"] .uV2eYG_modes {',
  '    gap: 6px;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_trailing {',
  '    flex: 1 1 auto !important;',
  '    justify-content: flex-end;',
  '    gap: 6px;',
  '  }',
  '  /* 固定控件钉死：add 28 / primary 34（mex 实测被压扁的瓶颈）*/',
  '  [data-mobile-nav="frame"] .uV2eYG_add,',
  '  [data-mobile-nav="frame"] .uV2eYG_primary {',
  '    flex: none !important;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_primary {',
  '    width: 34px !important;',
  '    height: 34px !important;',
  '  }',
  '  /* 模型选择器：可收缩 + ellipsis；effort 芯片不收缩 */',
  '  [data-mobile-nav="frame"] ._7KE1Ra_trigger {',
  '    max-width: min(100%, 180px) !important;',
  '    min-width: 0;',
  '  }',
  '  [data-mobile-nav="frame"] ._7KE1Ra_triggerLabel {',
  '    overflow: hidden;',
  '    text-overflow: ellipsis;',
  '    white-space: nowrap;',
  '    min-width: 0;',
  '  }',
  '',
  '  /* ---- 底部安全区（home indicator）---- */',
  '  [data-mobile-nav="frame"] .uV2eYG_root {',
  '    padding-bottom: calc(8px + env(safe-area-inset-bottom, 0px)) !important;',
  '  }',
  '',
  '  /* ---- 汉堡避让：聊天头标题左移，避免被 44px 汉堡盖住 ---- */',
  '  [data-mobile-nav="frame"] .wSkVaW_titleRow {',
  '    padding-left: 52px;',
  '  }',
  '  /* 汉堡避让：标签行（对话/轨迹等）同样让出左缘 */',
  '  [data-mobile-nav="frame"] .wSkVaW_tabs {',
  '    margin-left: 52px;',
  '  }',
  '  /* 移动端隐藏 Session log 下载（header utilities 槽） */',
  '  [data-mobile-nav="frame"] [data-slot="conversation.session.header.utilities"] {',
  '    display: none !important;',
  '  }',
  '}',
  '',
  '@media (max-width: 1023px) and (pointer: coarse) {',
  '  /* 44px 触控热区：::after 扩展命中区，不动视觉布局（TecFancy D6 手法）*/',
  '  [data-mobile-nav="frame"] .uV2eYG_add,',
  '  [data-mobile-nav="frame"] .uV2eYG_primary {',
  '    position: relative;',
  '  }',
  '  [data-mobile-nav="frame"] .uV2eYG_add::after,',
  '  [data-mobile-nav="frame"] .uV2eYG_primary::after {',
  "    content: '';",
  '    position: absolute;',
  '    inset: -8px;',
  '  }',
  '}',
]

export const COMPAT_CSS = LINES.join('\n')
