/**
 * 移动布局（DR1/DR7）：overlay 抽屉 + safe-area 基线 + 遮罩 + 汉堡。
 * 规则全部落在 @media (max-width: 1023px)；桌面由 (min-width: 1024px) 显式隐藏插件元素。
 * 关键约束：抽屉打开态必须 transform:none，禁止 translateX(0)
 * （identity transform 会成为 fixed 后代包含块，砸坏 portal 进侧栏的设置对话框）。
 */

const LINES = [
  '@media (max-width: 1023px) {',
  '  /* AppFrame：聊天列恒全宽；侧栏/详情列出流为浮层抽屉 */',
  '  [data-mobile-nav="frame"] {',
  '    position: relative !important;',
  '    grid-template-columns: minmax(0, 1fr) 0 0 !important;',
  '    padding-top: env(safe-area-inset-top, 0px) !important;',
  '  }',
  '  /* 三列显式钉位：侧栏列出流后剩余项不随 auto-placement 左移（TecFancy 踩坑） */',
  '  [data-mobile-nav="frame"] > :first-child { grid-column: 1; }',
  '  [data-mobile-nav="frame"] > :nth-child(2) { grid-column: 1; }',
  '  [data-mobile-nav="frame"] > :nth-child(3) { grid-column: 3; }',
  '',
  '  /* 左抽屉（侧栏） */',
  '  [data-mobile-nav="frame"] > [data-mobile-nav="drawer"] {',
  '    position: absolute !important;',
  '    inset: 0 auto 0 0 !important;',
  '    width: max-content;',
  '    max-width: 92vw;',
  '    z-index: 40 !important;',
  '    transform: translateX(-110%);',
  '    transition: transform .28s var(--ds-ease-in-out, ease-in-out);',
  '    background: var(--dsw-alias-bg-layer-1, #ffffff);',
  '    padding-top: env(safe-area-inset-top, 0px) !important;',
  '    border-right: none !important;',
  '  }',
  '  [data-mobile-nav="frame"]:not([data-sidebar-collapsed]) > [data-mobile-nav="drawer"] {',
  '    transform: none !important;',
  '  }',
  '',
  '  /* 右抽屉（details）：与左抽屉对称 */',
  '  [data-mobile-nav="frame"] > [data-mobile-nav="details"] {',
  '    position: absolute !important;',
  '    inset: 0 0 0 auto !important;',
  '    width: max-content;',
  '    max-width: 92vw;',
  '    z-index: 41 !important;',
  '    transform: translateX(110%);',
  '    transition: transform .28s var(--ds-ease-in-out, ease-in-out);',
  '    background: var(--dsw-alias-bg-layer-1, #ffffff);',
  '    padding-top: env(safe-area-inset-top, 0px) !important;',
  '  }',
  '  [data-mobile-nav="frame"]:not([data-details-collapsed]) > [data-mobile-nav="details"] {',
  '    transform: none !important;',
  '  }',
  '',
  '  /* 遮罩：z 39 < 抽屉 40；打开时可见 */',
  '  .dsh-xc-scrim {',
  '    display: none;',
  '    position: absolute;',
  '    inset: 0;',
  '    z-index: 39;',
  '    background: var(--dsw-alias-bg-mask-2, rgba(10, 14, 23, 0.42));',
  '    -webkit-tap-highlight-color: transparent;',
  '  }',
  '  [data-mobile-nav="frame"]:not([data-sidebar-collapsed]) > [data-mobile-nav="scrim"],',
  '  [data-mobile-nav="frame"]:not([data-details-collapsed]) > [data-mobile-nav="scrim"] {',
  '    display: block;',
  '  }',
  '',
  '  /* 汉堡：safe-area 偏移 + 44px 触控热区 */',
  '  .dsh-xc-ham {',
  '    position: fixed;',
  '    top: calc(10px + env(safe-area-inset-top, 0px));',
  '    left: 10px;',
  '    width: 44px;',
  '    height: 44px;',
  '    z-index: 60;',
  '    border: 1px solid rgba(127, 127, 127, 0.35);',
  '    border-radius: 13px;',
  '    background: var(--dsw-alias-bg-layer-1, #ffffff);',
  '    color: var(--dsw-alias-label-primary, #111827);',
  '    font-size: 22px;',
  '    display: flex;',
  '    align-items: center;',
  '    justify-content: center;',
  '    cursor: pointer;',
  '  }',
  '',
  '  /* shell.overlay 抬升（重启遮罩/模态/通知层）：宿主 overlayLayer 仅 z 20，',
  '     会被抽屉(40)/details(41)/汉堡(60)压住 -> 移动端统一抬到 1000，',
  '     保证 dsh-power-button 重启遮罩等浮层盖住全部移动 chrome（桌面媒体外零影响）*/',
  '  [data-shell-overlay] {',
  '    z-index: 1000 !important;',
  '  }',
  '',
  '  /* 抽屉/详情打开时隐藏汉堡（避免浮盖在抽屉/遮罩上；关闭途径：scrim 点击/点外/Escape/左滑）*/',
  '  [data-mobile-nav="frame"][data-xc-drawer] > .dsh-xc-ham,',
  '  [data-mobile-nav="frame"][data-xc-details] > .dsh-xc-ham {',
  '    display: none !important;',
  '  }',
  '',
  '  /* better-sidebar 右抽屉打开时也隐藏汉堡（和平共存下的显式让位） */',
  '  body:has([data-dsh-panel-host] .nArs4W_panel:not(.nArs4W_panelHidden)) .dsh-xc-ham {',
  '    display: none !important;',
  '  }',
  '',
  '  /* PWA standalone 应用内「刷新」入口（iOS 无下拉刷新时的手动刷新）*/',
  '  .dsh-xc-refresh {',
  '    border: 1px solid var(--dsw-alias-border-l1, #334155);',
  '    border-radius: 14px;',
  '    padding: 6px 12px;',
  '    font-size: 12px;',
  '    line-height: 1;',
  '    white-space: nowrap;',
  '    color: var(--dsw-alias-label-secondary, #94a3b8);',
  '    background: var(--dsw-alias-bg-layer-1, #ffffff);',
  '    cursor: pointer;',
  '  }',
  '',
  '  /* 触摸设备上用不到拖拽把手 */',
  '  [data-mobile-nav="frame"] > [data-side] { display: none !important; }',
  '}',
  '',
  '@media (min-width: 1024px) {',
  '  .dsh-xc-ham, .dsh-xc-scrim { display: none !important; }',
  '}',
]

export const LAYOUT_CSS = LINES.join('\n')