/**
 * misc — M3：设置/弹层/目录选择器/内容流/第三方兼容。
 * 所有规则落在 @media (max-width: 1023px)；dshmarket 反制额外加 <=560px 子媒体。
 * 关键：设置对话框渲染在抽屉 DOM 内（VOzbGW_overlay 为 position:fixed），
 * 抽屉 transform 会成为其包含块 -> 打开设置时必须解除 transform 陷阱（:has）。
 */

const LINES = [
  '@media (max-width: 1023px) {',
  '  /* ---- 设置/导出/目录选择对话框：抽屉内含 aria-modal 时解除 transform 陷阱并抬升 ---- */',
  '  [data-mobile-nav="frame"] > [data-mobile-nav="drawer"]:has([aria-modal="true"]) {',
  '    transform: none !important;',
  '    z-index: 50 !important;',
  '  }',
  '',
  '  /* ---- 设置面板：桌面 800px 对话框 -> 移动端全屏纵向 ---- */',
  '  [data-mobile-nav="frame"] .VOzbGW_panel {',
  '    width: 100vw !important;',
  '    max-width: 100vw !important;',
  '    height: 100dvh !important;',
  '    max-height: 100dvh !important;',
  '    border-radius: 0 !important;',
  '  }',
  '  /* nav 收成顶部横向可滚动按钮条（顺手修复宿主 flex-basis:0 压零宽 bug）*/',
  '  [data-mobile-nav="frame"] [role="dialog"][aria-modal="true"]:has(> nav) {',
  '    flex-direction: column !important;',
  '  }',
  '  [data-mobile-nav="frame"] [role="dialog"][aria-modal="true"]:has(> nav) > nav {',
  '    flex: none !important;',
  '    flex-direction: row !important;',
  '    overflow-x: visible !important;',
  '    box-sizing: border-box !important;',
  '    width: 100% !important;',
  '    padding: calc(10px + env(safe-area-inset-top, 0px)) 12px 6px !important;',
  '    gap: 8px !important;',
  '    align-items: center !important;',
  '  }',
  '  /* 页头标题（设置）不被 flex 压缩换行（div:not(:last-child)=标题；关闭按钮移入 nav 后为 button:first-child，不影响）*/',
  '  [data-mobile-nav="frame"] [role="dialog"][aria-modal="true"]:has(> nav) > nav > div:not(:last-child) {',
  '    flex: none !important;',
  '    white-space: nowrap !important;',
  '  }',
  '  [data-mobile-nav="frame"] [role="dialog"][aria-modal="true"]:has(> nav) > nav > div:last-child {',
  '    flex: 1 1 0 !important;',
  '    min-width: 0 !important;',
  '    flex-direction: row !important;',
  '    flex-wrap: nowrap !important;',
  '    gap: 6px !important;',
  '    overflow-x: auto !important;',
  '    scrollbar-width: thin;',
  '  }',
  '  [data-mobile-nav="frame"] [role="dialog"][aria-modal="true"]:has(> nav) > nav button {',
  '    flex: 0 0 auto !important;',
  '    height: 36px !important;',
  '    padding: 6px 12px !important;',
  '    justify-content: center !important;',
  '  }',
  '  /* 移入 nav 的关闭按钮（nav 直系 button）豁免导航条样式：维持 28px 圆钮 + 无 padding */',
  '  [data-mobile-nav="frame"] [role="dialog"][aria-modal="true"]:has(> nav) > nav > button {',
  '    flex: 0 0 auto !important;',
  '    height: 28px !important;',
  '    width: 28px !important;',
  '    padding: 0 !important;',
  '  }',
  '  [data-mobile-nav="frame"] [role="dialog"][aria-modal="true"]:has(> nav) > nav button > :last-child {',
  '    flex: 0 1 auto !important;',
  '    min-width: 0 !important;',
  '  }',
  '  /* 内容区滚动 + 底部安全区 */',
  '  [data-mobile-nav="frame"] [role="dialog"][aria-modal="true"]:has(> nav) > nav + div {',
  '    flex: 1 1 0 !important;',
  '    min-height: 0 !important;',
  '    padding-bottom: env(safe-area-inset-bottom, 0px) !important;',
  '  }',
  '',
  '  /* ---- 目录选择器：底部取消/确定固定单行 ---- */',
  '  [data-mobile-nav="frame"] [role="dialog"]:has(> div:last-child > button[aria-pressed]) > div:last-child {',
  '    flex: none !important;',
  '    display: grid !important;',
  '    grid-template-columns: minmax(0, 1fr) auto auto !important;',
  '    gap: 8px !important;',
  '    align-items: center !important;',
  '    padding: 10px 16px calc(10px + env(safe-area-inset-bottom, 0px)) !important;',
  '    border-top: 1px solid var(--dsw-alias-border-l1);',
  '  }',
  '',
  '  /* ---- popover 重锚定：composer/header 锚定弹层改居中定宽（上限 100vw-32）---- */',
  '  /* 玻璃卡 backdrop-filter 会困住 fixed 后代 -> 弹层打开时临时移除陷阱 */',
  '  [data-mobile-nav="frame"] .uV2eYG_card:has([role="menu"], [role="dialog"]) {',
  '    backdrop-filter: none !important;',
  '    -webkit-backdrop-filter: none !important;',
  '  }',
  '  /* composer 弹层（模型切换/权限等）：底部弹层（底部居中、贴 safe-area、向上弹开），',
  '     避免页面中央展开（v0.1.9 用户反馈）；header 菜单保持居中定宽 */',
  '  [data-slot="conversation.composer.bar"] [role="menu"],',
  '  [data-slot="conversation.composer.bar"] [role="dialog"] {',
  '    position: fixed !important;',
  '    top: auto !important;',
  '    left: 50% !important;',
  '    right: auto !important;',
  '    bottom: calc(12px + env(safe-area-inset-bottom, 0px)) !important;',
  '    transform: translateX(-50%) !important;',
  '    width: min(100% - 24px, 360px) !important;',
  '    max-width: 360px !important;',
  '    max-height: min(55dvh, 440px) !important;',
  '    overflow-y: auto;',
  '    z-index: 1200 !important;',
  '  }',
  '  [data-slot="conversation.session.header.actions"] ul[aria-label] {',
  '    position: fixed !important;',
  '    left: 50% !important;',
  '    top: 50% !important;',
  '    right: auto !important;',
  '    bottom: auto !important;',
  '    transform: translate(-50%, -50%) !important;',
  '    min-width: 0 !important;',
  '    max-width: calc(100vw - 32px) !important;',
  '    max-height: min(480px, calc(100dvh - 96px)) !important;',
  '    overflow-y: auto;',
  '    z-index: 1200 !important;',
  '  }',
  '',
  '  /* ---- agent-preset 底部弹层（body portal [role=menu]）---- */',
  '  [role="menu"]:has([class*="cubgiG_item"]) {',
  '    top: auto !important;',
  '    left: 50% !important;',
  '    right: auto !important;',
  '    bottom: 12px !important;',
  '    transform: translateX(-50%) !important;',
  '    width: min(100% - 24px, 360px) !important;',
  '    max-width: 360px !important;',
  '    max-height: min(55dvh, 440px) !important;',
  '    padding: 30px 6px 10px !important;',
  '    border-radius: 16px !important;',
  '    overflow-y: auto;',
  '    scrollbar-width: thin;',
  '  }',
  '  [role="menu"]:has([class*="cubgiG_item"])::before {',
  "    content: '';",
  '    position: absolute;',
  '    top: 6px;',
  '    left: 50%;',
  '    transform: translateX(-50%);',
  '    width: 36px;',
  '    height: 4px;',
  '    border-radius: 2px;',
  '    background: var(--dsw-alias-border-l2);',
  '  }',
  '  [role="menu"]:has([class*="cubgiG_item"])::-webkit-scrollbar {',
  '    width: 4px;',
  '  }',
  '',
  '  /* ---- 消息流：滚动条毛刺/侧边距/字号/操作行溢出 ---- */',
  '  [data-phase] [class*="_scrollBody"] {',
  '    scrollbar-gutter: auto !important;',
  '    scrollbar-width: none;',
  '  }',
  '  [data-phase] [class*="_scrollBody"]::-webkit-scrollbar {',
  '    display: none !important;',
  '    width: 0;',
  '    height: 0;',
  '  }',
  '  [data-phase] [class*="_scroll"]:not([class*="_scrollBody"]):has(p) {',
  '    padding-left: 20px;',
  '    padding-right: 20px;',
  '    font-size: 15px !important;',
  '  }',
  '  [data-phase] [class*="_actions"] {',
  '    overflow: hidden;',
  '  }',
  '  [data-phase] [class*="_actions"] [class*="_timeEnd"] {',
  '    flex: 0 1 auto;',
  '    min-width: 0;',
  '    overflow: hidden;',
  '    text-overflow: ellipsis;',
  '    white-space: nowrap !important;',
  '  }',
  '}',
  '',
  '@media (max-width: 560px) {',
  '  /* dshmarket >=1.20 移动端隐藏设置 nav 的死路反制（挂 data-xc-market-fix，由 compat 任务按开关控制）*/',
  '  html[data-xc-market-fix] [role="dialog"]:has([data-dsh-market-root]) > nav {',
  '    display: flex !important;',
  '  }',
  '}',
]

export const MISC_CSS = LINES.join('\n')