/**
 * pwa — PWA 面常量（M5）。
 *
 * SW 收敛策略（对 glass 版收敛）：
 *  - 只预缓存 boot 关键资源（index + 静态入口 + 图标 + 离线页），不再全量预取插件（首装 ~26MB 突刺）；
 *  - 内容寻址资源（/assets/*、/plugins/*?rev=）cache-first + 后台更新（rev=内容 SHA-1，升级自动取新）；
 *  - /api/* 与 /plugins/events（SSE/HMR）完全旁路；导航 network-first，失败回退内置离线页（诚实离线页，不做假壳）。
 * 关闭：localStorage 'dsh-mobile-xc.pwa' === 'off' 时客户端跳过注册并卸载已注册 SW（exports.disablePwa 预留设置项）。
 */

export const SW_VERSION = '202608-xc2'

export const MANIFEST_JSON = JSON.stringify(
  {
    id: '/',
    name: 'DeepSeek Harness',
    short_name: 'DSH',
    description: 'DeepSeek Harness 移动端',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    // 去 orientation 硬锁（决策：平板横屏友好）；theme_color 与默认深色主题对齐，运行时由 vendor ThemePresenter 的 meta 动态同步
    theme_color: '#0f172a',
    background_color: '#0f172a',
    icons: [
      { src: '/pwa/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/pwa/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      { src: '/pwa/icon-180.png', sizes: '180x180', type: 'image/png', purpose: 'any' }
    ]
  },
  null,
  2,
)

export const OFFLINE_HTML = [
  '<!doctype html>',
  '<html lang="zh-CN">',
  '<head>',
  '<meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1">',
  '<meta name="theme-color" content="#0f172a">',
  '<title>DSH · 离线</title>',
  '<style>',
  'body{margin:0;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;background:#0f172a;color:#e2e8f0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;text-align:center;padding:24px}',
  'img{width:72px;height:72px;border-radius:18px}',
  'h1{font-size:18px;margin:0;font-weight:600}',
  'p{font-size:14px;color:#94a3b8;margin:0}',
  'button{margin-top:10px;padding:10px 28px;border:1px solid #334155;border-radius:12px;background:rgba(148,163,184,.12);color:#e2e8f0;font-size:14px;cursor:pointer}',
  '</style>',
  '</head>',
  '<body>',
  '<img src="/pwa/icon-192.png" alt="DSH">',
  '<h1>离线中</h1>',
  '<p>当前网络不可用，恢复后自动重连</p>',
  '<button onclick="location.reload()">重试</button>',
  '</body>',
  '</html>',
].join('\n')

export const REGISTER_SCRIPT = [
  '<script data-dsh-xc-pwa>',
  '(function () {',
  "  if (!('serviceWorker' in navigator)) return;",
  "  if (typeof localStorage !== 'undefined' && localStorage.getItem('dsh-mobile-xc.pwa') === 'off') return;",
  "  window.addEventListener('load', function () {",
  "    navigator.serviceWorker.register('/sw.js', { scope: '/', updateViaCache: 'none' }).catch(function () {});",
  '  });',
  '})();',
  '</script>',
].join('\n')

/** 注入 </head> 前（tapIndex 幂等：data-dsh-xc-pwa）。 */
export const HEAD_EXTRA = [
  '<link rel="apple-touch-icon" href="/pwa/icon-180.png">',
  '<meta name="theme-color" content="#0f172a">',
  REGISTER_SCRIPT,
].join('\n    ')

const STATIC_URLS = [
  "'/manifest.webmanifest'",
  "'/favicon.svg'",
  "'/pwa/icon-192.png'",
  "'/pwa/icon-512.png'",
  "'/pwa/icon-180.png'",
]

export const SW_SOURCE = [
  '/* dsh-mobile-xc service worker — generated from src/pwa.ts */',
  "'use strict';",
  'var VERSION = ' + JSON.stringify(SW_VERSION) + ';',
  "var CACHE = 'dsh-pwa-' + VERSION;",
  'var OFFLINE = ' + JSON.stringify(OFFLINE_HTML) + ';',
  'var STATIC_URLS = [' + STATIC_URLS.join(',') + '];',
  'var BOOT_ASSET_LIMIT = 12;',
  '',
  'function collectBootAssets() {',
  "  return fetch('/', { cache: 'no-store' })",
  '    .then(function (res) { return res.text(); })',
  '    .then(function (html) {',
  '      var urls = [];',
  '      var re = /(?:src|href)=\"(\\/assets\\/[^\"]+)\"/g;',
  '      var m;',
  '      while ((m = re.exec(html)) && urls.length < BOOT_ASSET_LIMIT) urls.push(m[1]);',
  '      return urls;',
  '    })',
  '    .catch(function () { return []; });',
  '}',
  '',
  "self.addEventListener('install', function (event) {",
  '  event.waitUntil(',
  '    Promise.all([',
  '      caches.open(CACHE).then(function (cache) {',
  '        var put = function (url) {',
  '          return fetch(url).then(function (res) {',
  '            if (res.ok) return cache.put(url, res);',
  '          }).catch(function () {});',
  '        };',
  "        var tasks = STATIC_URLS.map(put);",
  "        tasks.push(cache.put('/offline', new Response(OFFLINE, { headers: { 'content-type': 'text/html; charset=utf-8' } })));",
  "        return collectBootAssets().then(function (urls) {",
  '          return Promise.all(urls.map(function (u) { return put(u); }));',
  '        }).then(function () { return Promise.all(tasks); });',
  '      }),',
  '      self.skipWaiting()',
  '    ])',
  '  );',
  '});',
  '',
  "self.addEventListener('activate', function (event) {",
  '  event.waitUntil(',
  '    caches.keys().then(function (keys) {',
  '      return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));',
  '    }).then(function () { return self.clients.claim(); })',
  '  );',
  '});',
  '',
  "self.addEventListener('fetch', function (event) {",
  '  var req = event.request;',
  "  if (req.method !== 'GET') return;",
  '  var url = new URL(req.url);',
  "  if (url.origin !== self.location.origin) return;",
  '  var path = url.pathname;',
  '',
  '  /* 鉴权/实时/动态流量：完全旁路 */',
  "  if (path === '/api' || path.indexOf('/api/') === 0) return;",
  "  if (path === '/plugins/events') return;",
  '',
  '  /* 导航：network-first，失败回退离线页 */',
  "  if (req.mode === 'navigate') {",
  '    event.respondWith(',
  '      fetch(req).then(function (res) {',
  '        if (res && res.ok) {',
  '          var clone = res.clone();',
  '          caches.open(CACHE).then(function (cache) { return cache.put(req, clone); }).catch(function () {});',
  '        }',
  '        return res;',
  '      }).catch(function () {',
  "        return caches.match('/offline');",
  '      })',
  '    );',
  '    return;',
  '  }',
  '',
  '  /* 内容寻址：cache-first + 后台更新（升级后 rev/哈希变化自动取新，不会吃到陈旧 bundle）*/',
  '  var cacheable = path.indexOf("/assets/") === 0',
  "    || (path.indexOf('/plugins/') === 0 && path.indexOf('/plugins/events') !== 0)",
  "    || path.indexOf('/pwa/') === 0",
  "    || path === '/manifest.webmanifest'",
  "    || path === '/favicon.svg';",
  '  if (!cacheable) return;',
  '',
  '  event.respondWith(',
  '    caches.open(CACHE).then(function (cache) {',
  '      return cache.match(req).then(function (cached) {',
  '        if (cached) {',
  '          fetch(req).then(function (res) {',
  '            if (res && res.ok) cache.put(req, res);',
  '          }).catch(function () {});',
  '          return cached;',
  '        }',
  '        return fetch(req).then(function (res) {',
  '          if (res && res.ok) cache.put(req, res.clone());',
  '          return res;',
  '        }).catch(function () {',
  "          return new Response('', { status: 503, statusText: 'Offline' });",
  '        });',
  '      });',
  '    })',
  '  );',
  '});',
].join('\n')